-- MySQL Script generated by MySQL Workbench
-- Mon Oct  8 20:34:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema administracion_colegio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `administracion_colegio` ;

-- -----------------------------------------------------
-- Schema administracion_colegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `administracion_colegio` DEFAULT CHARACTER SET latin1 ;
USE `administracion_colegio` ;

-- -----------------------------------------------------
-- Table `administracion_colegio`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`estados` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`estados` (
  `estado_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`generos` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`generos` (
  `genero_id` INT(11) NOT NULL,
  `sexo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`genero_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`instituciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`instituciones` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`instituciones` (
  `institucion_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`institucion_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`lugares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`lugares` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`lugares` (
  `lugar_id` INT(11) NOT NULL AUTO_INCREMENT,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`lugar_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 233
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`nivel_educacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`nivel_educacion` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`nivel_educacion` (
  `nivel_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`nivel_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`estado_civil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`estado_civil` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`estado_civil` (
  `estado_civil_id` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`estado_civil_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`usuario` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`usuario` (
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `clave` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(2) NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `estado_id` INT(11) NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_usuario_estados1_idx` (`estado_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`personal` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`personal` (
  `personal_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `especialidad_id` INT(11) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `mail` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_creacion` DATE NULL DEFAULT NULL,
  `usuario_creacion` VARCHAR(45) NULL DEFAULT NULL,
  `genero_id` INT(11) NULL DEFAULT NULL,
  `estado_civil_id` INT(11) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `fechaNac` DATE NULL DEFAULT NULL,
  `fechaLaboral` DATE NULL DEFAULT NULL,
  `aniosExperiencia` INT(11) NULL DEFAULT NULL,
  `cargas` INT(11) NULL DEFAULT NULL,
  `curriculum_direccion` VARCHAR(200) NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  `foto` BLOB NULL,
  `cedula` VARCHAR(10) NULL,
  PRIMARY KEY (`personal_id`),
  INDEX `profesores_generos_idx` (`genero_id` ASC) VISIBLE,
  INDEX `profesores_estado_civil_idx` (`estado_civil_id` ASC) VISIBLE,
  INDEX `profesores_especialidades_fk_idx` (`especialidad_id` ASC) VISIBLE,
  INDEX `profesor_id` (`personal_id` ASC) VISIBLE,
  INDEX `profesor_id_2` (`personal_id` ASC) VISIBLE,
  INDEX `fk_personal_usuarios1_idx` (`usuario_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`periodo_electivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`periodo_electivo` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`periodo_electivo` (
  `periodo_id` INT(11) NOT NULL AUTO_INCREMENT,
  `anio_inicio` VARCHAR(45) NULL DEFAULT NULL,
  `anio_fin` VARCHAR(45) NULL DEFAULT NULL,
  `estado_id` INT(11) NULL DEFAULT NULL,
  `fecha_inicio_periodo` DATE NULL DEFAULT NULL,
  `fecha_fin_periodo` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`periodo_id`),
  INDEX `periodo_electivo_estados_fk_idx` (`estado_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`cursos` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`cursos` (
  `curso_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `jornada` VARCHAR(45) NULL DEFAULT NULL,
  `cant_alumnos` VARCHAR(45) NULL DEFAULT NULL,
  `paralelo` VARCHAR(45) NULL DEFAULT NULL,
  `estado_id` INT(11) NULL DEFAULT NULL,
  `nivel_id` INT(11) NULL DEFAULT NULL,
  `usuario_creacion` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_creacion` DATE NULL DEFAULT NULL,
  `dirigente` INT(11) NOT NULL,
  `periodo_electivo_periodo_id` INT(11) NOT NULL,
  PRIMARY KEY (`curso_id`),
  INDEX `cursos_estados_fk_idx` (`estado_id` ASC) VISIBLE,
  INDEX `cursos_niveles_fk_idx` (`nivel_id` ASC) VISIBLE,
  INDEX `fk_cursos_personal1_idx` (`dirigente` ASC) VISIBLE,
  INDEX `fk_cursos_periodo_electivo1_idx` (`periodo_electivo_periodo_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`alumno` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`alumno` (
  `cedula` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `genero_id` INT(11) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `lugar_id` INT(11) NOT NULL,
  `foto_direccion` VARCHAR(200) NULL,
  `fecha_creacion` DATE NOT NULL,
  `usuario_creacion` VARCHAR(45) NULL DEFAULT NULL,
  `estado_id` INT(11) NOT NULL,
  `instituciones_id` INT(11) NOT NULL,
  `observacion` VARCHAR(250) NULL DEFAULT NULL,
  `certificado_direccion` VARCHAR(200) NULL DEFAULT NULL,
  `pension` DOUBLE NOT NULL,
  `cursos_curso_id` INT(11) NULL,
  PRIMARY KEY (`cedula`),
  INDEX `alumnos_genero_id_fk_idx` (`genero_id` ASC) VISIBLE,
  INDEX `alumnos_estados_idx` (`estado_id` ASC) VISIBLE,
  INDEX `alumnos_instituciones_fk_idx` (`instituciones_id` ASC) VISIBLE,
  INDEX `alumnos_lugares_fk_idx` (`lugar_id` ASC) VISIBLE,
  INDEX `fk_alumnos_cursos1_idx` (`cursos_curso_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`factura` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`factura` (
  `factura_id` INT(11) NOT NULL AUTO_INCREMENT,
  `n_factura` INT(11) NULL DEFAULT NULL,
  `orden_pago_id` INT(11) NULL DEFAULT NULL,
  `modo_pago_id` INT(11) NULL DEFAULT NULL,
  `fecha_pago` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`factura_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`administrador` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`administrador` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `foto` BLOB NULL,
  `cedula` VARCHAR(45) NULL,
  `usuarios_usuario_id` INT NOT NULL,
  `cedula_copy1` VARCHAR(10) NULL,
  PRIMARY KEY (`admin_id`),
  INDEX `fk_administradores_usuarios1_idx` (`usuarios_usuario_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`materia` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`materia` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `imagen` BLOB NULL,
  `descripcion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`parentezco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`parentezco` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`parentezco` (
  `idparentezco` INT NOT NULL AUTO_INCREMENT,
  `parentezco` VARCHAR(45) NULL,
  PRIMARY KEY (`idparentezco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`autorizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`autorizacion` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`autorizacion` (
  `id_padre` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `estado_civil_id` INT(11) NOT NULL,
  `alumno_id` INT(11) NOT NULL,
  `tipo` VARCHAR(45) NULL,
  `genero_id` INT(11) NOT NULL,
  `cedula` VARCHAR(10) NULL,
  `idparentezco` INT NOT NULL,
  `usuario_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_padre`),
  INDEX `fk_padre_estado_civil1_idx` (`estado_civil_id` ASC) VISIBLE,
  INDEX `fk_autorizacion_generos1_idx` (`genero_id` ASC) VISIBLE,
  INDEX `fk_autorizacion_parentezco1_idx` (`idparentezco` ASC) VISIBLE,
  INDEX `fk_autorizacion_usuario1_idx` (`usuario_usuario_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`documento` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`documento` (
  `link` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `alumno_cedula` VARCHAR(20) NOT NULL,
  INDEX `fk_documento_alumno1_idx` (`alumno_cedula` ASC) VISIBLE,
  PRIMARY KEY (`alumno_cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`grupo_sanguineo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`grupo_sanguineo` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`grupo_sanguineo` (
  `idgrupo_sanguineo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idgrupo_sanguineo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`datos_medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`datos_medicos` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`datos_medicos` (
  `tiene_discapacidad` TINYINT NULL,
  `porcentaje_discapacidad` INT NULL,
  `tipo_discapacidad` VARCHAR(45) NULL,
  `alumnos_cedula` VARCHAR(20) NOT NULL,
  `idgrupo_sanguineo` INT NULL,
  INDEX `fk_datos_medicos_alumnos1_idx` (`alumnos_cedula` ASC) VISIBLE,
  PRIMARY KEY (`alumnos_cedula`),
  INDEX `fk_datos_medicos_grupo_sanguineo1_idx` (`idgrupo_sanguineo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`detalle_materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`detalle_materia` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`detalle_materia` (
  `id_detalle_materia` INT NOT NULL AUTO_INCREMENT,
  `materia_id_materia` INT NOT NULL,
  `personal_personal_id` INT(11) NOT NULL,
  `cursos_curso_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_detalle_materia`),
  INDEX `fk_detalle_materia_materia1_idx` (`materia_id_materia` ASC) VISIBLE,
  INDEX `fk_detalle_materia_personal1_idx` (`personal_personal_id` ASC) VISIBLE,
  INDEX `fk_detalle_materia_cursos1_idx` (`cursos_curso_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`horario` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`horario` (
  `id_horario` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(45) NULL,
  `hora_inicio` TIME NULL,
  `hora_fin` TIME NULL,
  `detalle_materia_id_detalle_materia` INT NOT NULL,
  PRIMARY KEY (`id_horario`),
  INDEX `fk_horario_detalle_materia1_idx` (`detalle_materia_id_detalle_materia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`mensaje` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`mensaje` (
  `id_mensajes` INT NOT NULL AUTO_INCREMENT,
  `asunto` VARCHAR(35) NULL,
  `contenido` VARCHAR(200) NULL,
  `fecha` DATETIME NULL,
  `tipo` VARCHAR(25) NULL,
  PRIMARY KEY (`id_mensajes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`adjunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`adjunto` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`adjunto` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `mensaje_id` INT NOT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `fk_adjunto_mensajes1_idx` (`mensaje_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`actividad` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`actividad` (
  `id_Actividad` INT NOT NULL AUTO_INCREMENT,
  `dia` INT NULL,
  `mes` INT NULL,
  `año` INT NULL,
  `descripcion` VARCHAR(75) NULL,
  `lugar` VARCHAR(45) NULL,
  `hora` DATETIME NULL,
  `duración` TIME NULL,
  PRIMARY KEY (`id_Actividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`citacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`citacion` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`citacion` (
  `id_Citacion` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `duración` TIME NULL,
  `mensaje` INT NOT NULL,
  `hora` TIMESTAMP(5) NULL,
  PRIMARY KEY (`id_Citacion`),
  INDEX `fk_Citación_mensaje1_idx` (`mensaje` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`citacion_padre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`citacion_padre` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`citacion_padre` (
  `id_citacion_padre` INT NOT NULL,
  `padre` INT NOT NULL,
  `citacion` INT NOT NULL,
  PRIMARY KEY (`id_citacion_padre`),
  INDEX `fk_citacion_padre_autorizacion1_idx` (`padre` ASC) VISIBLE,
  INDEX `fk_citacion_padre_Citación1_idx` (`citacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administracion_colegio`.`citacion_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administracion_colegio`.`citacion_curso` ;

CREATE TABLE IF NOT EXISTS `administracion_colegio`.`citacion_curso` (
  `id_citacion_curso` INT NOT NULL AUTO_INCREMENT,
  `profesor` INT(11) NOT NULL,
  `citacion` INT NOT NULL,
  PRIMARY KEY (`id_citacion_curso`),
  INDEX `fk_citación_curso_personal1_idx` (`profesor` ASC) VISIBLE,
  INDEX `fk_citación_curso_citación1_idx` (`citacion` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
