create database administracion_colegio;
use administracion_colegio;

describe alumno;
describe estados;
describe documento;
describe personal; 
describe usuario;
describe administrador;
describe cursos; 

select * from actividad;
select * from adjunto;
select * from administrador;
select * from alumno;
select * from autorizacion;
select * from autorizado;
select * from citacion;
select * from citacion_curso;
select * from citacion_padre;
select * from cursos;
select * from datos_medicos;
select * from detalle_materia;
select * from documento;
select * from estado_civil;
select * from estados;
select * from factura;
select * from generos;
select * from grupo_sanguineo;
select * from horario;
select * from instituciones;
select * from lugares;
select * from materia;
select * from mensaje;
select * from nivel_educacion;
select * from parentesco;
select * from periodo_electivo;
select * from personal;
select * from usuario;